version: '3.8'

services:
  elasticsearch:
    build: 
      context: ./elasticsearch
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - ELASTICSEARCH_HOST=elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./data:/app/data

volumes:
  esdata:
    driver: local